version: '3.8'
services:
  avisense_backend:
    build: .
    image: backend_img
    container_name: backend_container
    command: uvicorn backend:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    ports:
      - "8000:8000"

#run: sudo docker compose up -d --build --force-recreate avisense_backend
# run locally : uvicorn backend:app --host 0.0.0.0 --port 8000 --reload

